### ISSUE TITLE
future of this repo

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastiktools#3]
Hi @DerThorsten,

ilastik is still getting good use out of your `ilastiktools`. In principle we want to move everything we build/maintain to conda-forge. Over the years there were small developments/fixes in the ilastik fork. Do you want to continue to maintain this Repo? If not you could transfer it to the ilastik org (I guess I'd have to rename our for first) and we'd incorporate changes there and have this as the source for the conda-forge build.

Cheers
Dominik

**Comment by DerThorsten** [comment]
> Hi @DerThorsten,
> 
> ilastik is still getting good use out of your `ilastiktools`. In principle we want to move everything we build/maintain to conda-forge. Over the years there were small developments/fixes in the ilastik fork. Do you want to continue to maintain this Repo? 

Happy to help and moving everything, including this, to conda-forge is a good idea!

> If not you could transfer it to the ilastik org (I guess I'd have to rename our for first) and we'd incorporate changes there and have this as the source for the conda-forge build.

So we could move it to ilastik anyhow for consistency.
You can make whatever PR you want to make to this repo and I will merge it.

So whatever is best for you =)

> 
> Cheers Dominik

**Comment by DerThorsten** [comment]
I am almost tempted to just rewrite this with pybind11 / nanobind without any other dependencies (ie no vigra)

**Comment by DerThorsten** [comment]
@k-dominik  fyi, I also added you as  Collaborator to this Repo, you should have an invitation

**Comment by k-dominik** [comment]
Hey thank you for the quick response. In the meantime I tried out the transfer of a repo to the org that already has a fork and it works nicely if the fork is renamed, first.

In the end this is your repo, but I would prefer to transfer it to the ilastik org, so that everyone there has full access to it. I have renamed out fork for now, but this does not mean that you _have_ to transfer it - up to you.

**Comment by DerThorsten** [comment]
> In the end this is your repo, but I would prefer to transfer it to the ilastik org, so that everyone there has full access to it. I have renamed out fork for now, but this does not mean that you _have_ to transfer it - up to you.

Absolutely, so lets do that!

**Comment by DerThorsten** [comment]
So I cannot do the transfer to Ilastik, I dont have enough permissions.
Feel free to try if you can do it

**Comment by k-dominik** [comment]
I updated the permissions, could you please try again?

**Comment by DerThorsten** [comment]
> I updated the permissions, could you please try again?

done

**Comment by k-dominik** [comment]
thank you @DerThorsten !! 🙌
